# Generated by Django 4.2.11 on 2024-03-18 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ean_cod',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
