# Generated by Django 4.2.11 on 2024-03-16 20:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('sale_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sale_date', models.DateField()),
                ('sale_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale_status', models.CharField(max_length=50)),
                ('payment_methods', models.CharField(max_length=100)),
                ('associated_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('products', models.ManyToManyField(related_name='sales', to='product.product')),
            ],
        ),
    ]
