# Generated by Django 4.2.11 on 2024-03-17 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_alter_sale_sale_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='payment_methods',
            field=models.CharField(choices=[('In Cash', 'In Cash'), ('1x - Credit Card', '1x - Credit Card'), ('2x - Credit Card', '2x - Credit Card'), ('3x - Credit Card', '3x - Credit Card'), ('4x - Credit Card', '4x - Credit Card')], max_length=100),
        ),
    ]
