# Generated by Django 4.2.11 on 2024-03-18 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_seller_function_alter_seller_seller_id'),
        ('sale', '0004_alter_sale_sale_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='associated_seller',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='seller.seller'),
            preserve_default=False,
        ),
    ]
