# Generated by Django 4.2.11 on 2024-03-16 20:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('group_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('products', models.ManyToManyField(related_name='groups', to='product.product')),
            ],
        ),
    ]
