# Generated by Django 4.2.11 on 2024-03-18 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productgroup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productgroup',
            name='group_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
